// Generated by gencpp from file asr_navfn/MakeNavPlan.msg
// DO NOT EDIT!


#ifndef ASR_NAVFN_MESSAGE_MAKENAVPLAN_H
#define ASR_NAVFN_MESSAGE_MAKENAVPLAN_H

#include <ros/service_traits.h>


#include <asr_navfn/MakeNavPlanRequest.h>
#include <asr_navfn/MakeNavPlanResponse.h>


namespace asr_navfn
{

struct MakeNavPlan
{

typedef MakeNavPlanRequest Request;
typedef MakeNavPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MakeNavPlan
} // namespace asr_navfn


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asr_navfn::MakeNavPlan > {
  static const char* value()
  {
    return "8ffef29bc8b086289124c16a8daa989d";
  }

  static const char* value(const ::asr_navfn::MakeNavPlan&) { return value(); }
};

template<>
struct DataType< ::asr_navfn::MakeNavPlan > {
  static const char* value()
  {
    return "asr_navfn/MakeNavPlan";
  }

  static const char* value(const ::asr_navfn::MakeNavPlan&) { return value(); }
};


// service_traits::MD5Sum< ::asr_navfn::MakeNavPlanRequest> should match
// service_traits::MD5Sum< ::asr_navfn::MakeNavPlan >
template<>
struct MD5Sum< ::asr_navfn::MakeNavPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asr_navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::asr_navfn::MakeNavPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asr_navfn::MakeNavPlanRequest> should match
// service_traits::DataType< ::asr_navfn::MakeNavPlan >
template<>
struct DataType< ::asr_navfn::MakeNavPlanRequest>
{
  static const char* value()
  {
    return DataType< ::asr_navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::asr_navfn::MakeNavPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asr_navfn::MakeNavPlanResponse> should match
// service_traits::MD5Sum< ::asr_navfn::MakeNavPlan >
template<>
struct MD5Sum< ::asr_navfn::MakeNavPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asr_navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::asr_navfn::MakeNavPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asr_navfn::MakeNavPlanResponse> should match
// service_traits::DataType< ::asr_navfn::MakeNavPlan >
template<>
struct DataType< ::asr_navfn::MakeNavPlanResponse>
{
  static const char* value()
  {
    return DataType< ::asr_navfn::MakeNavPlan >::value();
  }
  static const char* value(const ::asr_navfn::MakeNavPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASR_NAVFN_MESSAGE_MAKENAVPLAN_H
